name: JbotsportsWatch
options:
  bundleIdPrefix: org.jbotsports
  deploymentTarget:
    watchOS: '10.0'
settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCT_NAME: JbotsportsWatch

configs:
  Debug: debug
  Release: release

targets:
  JbotsportsWatch Watch App:
    type: application
    platform: watchOS
    sources:
      - path: TennisCtlWatchApp.swift
      - path: BLE
      - path: Models
      - path: ViewModels
      - path: Views
      - path: Info.plist
      - path: Assets.xcassets
        buildPhase: resources
      - path: en.lproj/Localizable.strings
        buildPhase: resources
      - path: zh-Hans.lproj/Localizable.strings
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.jbotsports.v6.watchapp
        PRODUCT_NAME: JbotsportsWatch
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: JbotsportsWatch
        INFOPLIST_KEY_CFBundleName: JbotsportsWatch
        INFOPLIST_KEY_WKApplication: YES
        INFOPLIST_KEY_WKWatchOnly: YES
        INFOPLIST_KEY_NSBluetoothAlwaysUsageDescription: Need Bluetooth to connect tennis machine.
